import 'package:flutter/material.dart';
import 'package:practice_tabbar/components/card_chart.dart';

class AllChat extends StatefulWidget {
  const AllChat({super.key});

  @override
  State<AllChat> createState() => _AllChatState();
}

class _AllChatState extends State<AllChat> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.grey[200],
      body: SingleChildScrollView(
        scrollDirection: Axis.vertical,
        padding: const EdgeInsets.only(bottom: 30),
        physics: const AlwaysScrollableScrollPhysics(),
        child: Container(
          color: Colors.grey[200],
          child: Column(
            mainAxisAlignment: MainAxisAlignment.start,
            children: [
              const CardChart(
                colorButton: Color(0xFF33b5e5),
                date: "11:38 AM",
                color: Colors.grey,
                atlern: "@",
                icon: "assets/png/mute.png",
                active: "assets/png/chart.png",
                image: "assets/png/1.png",
                username: "Pizza",
                message: "Hello",
                detail: "Yes, they are necessary",
                verify: "assets/png/001-voice-chat.png",
              ),
              buildDivider(),
              const CardChart(
                colorButton: Color(0xFF33b5e5),
                date: "Thu",
                atlern: "1",
                icon: "assets/png/social-media.png",
                image: "assets/png/image.png",
                username: "Telegram Support",
                message: "Support",
                detail: "Yes it happened",
              ),
              buildDivider(),
              const CardChart(
                read: "assets/png/read.png",
                detail: "Will it ever happen",
                date: "May 02",
                color: Colors.grey,
                image: "assets/png/image copy.png",
                username: "Marilyn",
              ),
              buildDivider(),
              const CardChart(
                colorButton: Colors.grey,
                date: "May 02",
                read: "assets/png/read.png",
                atlern: "2",
                icon: "assets/png/mute.png",
                image: "assets/png/gordon.png",
                username: "Dmitirij",
                message: "Gordon",
                detail: "Maybe...",
                color: Colors.grey,
              ),
              buildDivider(),
              const CardChart(
                colorButton: Color(0xFF33b5e5),
                date: "11:38 AM",
                color: Colors.grey,
                atlern: "@",
                icon: "assets/png/mute.png",
                active: "assets/png/chart.png",
                image: "assets/png/1.png",
                username: "Pizza",
                message: "Hello",
                detail: "Yes, they are necessary",
                verify: "assets/png/001-voice-chat.png",
              ),
              buildDivider(),
              const CardChart(
                colorButton: Color(0xFF33b5e5),
                date: "Thu",
                atlern: "1",
                icon: "assets/png/social-media.png",
                image: "assets/png/image.png",
                username: "Telegram Support",
                message: "Support",
                detail: "Yes it happened",
              ),
              buildDivider(),
              const CardChart(
                read: "assets/png/read.png",
                detail: "Will it ever happen",
                date: "May 02",
                color: Colors.grey,
                image: "assets/png/image copy.png",
                username: "Marilyn",
              ),
              buildDivider(),
              const CardChart(
                colorButton: Colors.grey,
                date: "May 02",
                read: "assets/png/read.png",
                atlern: "2",
                icon: "assets/png/mute.png",
                image: "assets/png/gordon.png",
                username: "Dmitirij",
                message: "Gordon",
                color: Colors.grey,
                detail: "Maybe...",
              ),
              buildDivider(),
              const CardChart(
                colorButton: Color(0xFF33b5e5),
                date: "11:38 AM",
                color: Colors.grey,
                atlern: "@",
                icon: "assets/png/mute.png",
                active: "assets/png/chart.png",
                image: "assets/png/1.png",
                username: "Pizza",
                message: "Hello",
                detail: "Yes, they are necessary",
                verify: "assets/png/001-voice-chat.png",
              ),
              buildDivider(),
              const CardChart(
                colorButton: Color(0xFF33b5e5),
                date: "Thu",
                atlern: "1",
                icon: "assets/png/social-media.png",
                image: "assets/png/image.png",
                username: "Telegram Support",
                message: "Support",
                detail: "Yes it happened",
              ),
              buildDivider(),
              const CardChart(
                read: "assets/png/read.png",
                detail: "Will it ever happen",
                date: "May 02",
                color: Colors.grey,
                image: "assets/png/image copy.png",
                username: "Marilyn",
              ),
              buildDivider(),
              const CardChart(
                colorButton: Colors.grey,
                date: "May 02",
                read: "assets/png/read.png",
                atlern: "2",
                icon: "assets/png/mute.png",
                image: "assets/png/gordon.png",
                username: "Dmitirij",
                message: "Gordon",
                detail: "Maybe...",
                color: Colors.grey,
              ),
              buildDivider(),
              const CardChart(
                colorButton: Color(0xFF33b5e5),
                date: "11:38 AM",
                color: Colors.grey,
                atlern: "@",
                icon: "assets/png/mute.png",
                active: "assets/png/chart.png",
                image: "assets/png/1.png",
                username: "Pizza",
                message: "Hello",
                detail: "Yes, they are necessary",
                verify: "assets/png/001-voice-chat.png",
              ),
              buildDivider(),
              const CardChart(
                colorButton: Color(0xFF33b5e5),
                date: "Thu",
                atlern: "1",
                icon: "assets/png/social-media.png",
                image: "assets/png/image.png",
                username: "Telegram Support",
                message: "Support",
                detail: "Yes it happened",
              ),
              buildDivider(),
              const CardChart(
                read: "assets/png/read.png",
                detail: "Will it ever happen",
                date: "May 02",
                color: Colors.grey,
                image: "assets/png/image copy.png",
                username: "Marilyn",
              ),
              buildDivider(),
              const CardChart(
                colorButton: Colors.grey,
                date: "May 02",
                read: "assets/png/read.png",
                atlern: "2",
                icon: "assets/png/mute.png",
                image: "assets/png/gordon.png",
                username: "Dmitirij",
                message: "Gordon",
                detail: "Maybe...",
                color: Colors.grey,
              ),
              buildDivider(),
            ],
          ),
        ),
      ),
    );
  }

  Widget buildDivider() {
    return Container(
      height: 1,
      width: double.infinity,
      color: Colors.grey.withOpacity(0.2),
      margin: const EdgeInsets.only(left: 90),
    );
  }
}
